#!/usr/bin/env ruby

require 'fileutils'
require 'optparse'

HELP = <<END

Print information associated with the git tag named <tag> in the git repository
at <dir>. If <dir> is omitted, the current working directory is used.

Options:
END

info = []

parser = OptionParser.new do |opts|
  opts.banner = 'Usage: taginfo [<option> ...] [<dir>] <tag>'

  opts.separator HELP

  opts.on('-d', '--date', 'Print date of tagged commit') { info << :date }
  opts.on('-m', '--message', 'Print most recent tag message') { info << :msg }

  opts.on('-h', '--help', 'Print this message and exit') do
    puts opts
    exit
  end
end

begin
  parser.parse!
rescue OptionParser::ParseError => err
  warn(err)
  exit(1)
end

unless [1, 2].include?(ARGV.size)
  warn(parser)
  exit(1)
end
tag = ARGV[-1]

if ARGV.size == 2
  begin
    FileUtils.cd(ARGV[0])
  rescue => err
    warn(err)
    exit(1)
  end
end

show = `git show #{tag} | tail -n +5`

output = info.map do |type|
  if type == :date
    show.split(/\ncommit/)[1][/Date:\s+(.+?)$/, 1]
  elsif type == :msg
    show.split(/\n(tag|commit)/)[0]
  end
end.join("\n\n")

puts output
