#!/usr/bin/env bash

STATUS=0

if [[ $# == 0 ]] || [[ "$1" == '--help' ]] || [[ "$1" == '-h' ]]; then
	echo 'Usage: explode <dir> ...' >&2
	if [[ $# == 0 ]]; then
		STATUS=1
	fi
	exit $STATUS
fi

for ARG in "$@"; do
	if [[ ! -d "$ARG" ]]; then
		echo "$ARG: not a directory" >&2
		STATUS=1
		continue
	fi

	WD=`pwd`
	cd "$ARG"
	if [[ `ls -A` ]]; then
		mv -n `ls -A` ../
	fi
	cd "$WD"

	rmdir "$ARG"
done

exit $STATUS
