#!/usr/bin/env bash

STATUS=0

if [[ $# == 0 ]] || [[ "$1" == "--help" ]] || [[ "$1" == "-h" ]]; then
	>&2 echo "Usage: explode <dir> ..."
	if [[ $# == 0 ]]; then
		STATUS=1
	fi
	exit $STATUS
fi

for ARG in "$@"; do
	if [[ ! -d "$ARG" ]]; then
		>&2 echo "$ARG: not a directory"
		STATUS=1
		continue
	fi

	WD=`pwd`
	cd "$ARG"
	if [[ `ls -A` ]]; then
		mv -n `ls -A` ../
	fi
	cd "$WD"

	rmdir "$ARG"
done

exit $STATUS
