#!/usr/bin/env bash

if [[ $# == 0 ]] || [[ "$1" == '--help' ]] || [[ "$1" == '-h' ]]; then
	echo 'Usage: explode <dir> ...' >&2
	[[ $# != 0 ]]; exit $?
fi

for arg in "$@"; do
	if [[ ! -d "$arg" ]]; then
		echo "$arg: not a directory" >&2
		status=1
		continue
	fi

	cd "$arg"
	if [[ `ls -A` ]]; then
		mv -n `ls -A` ../
	fi
	cd "$OLDPWD"

	rmdir "$arg"
done

exit $status
