#!/usr/bin/env bash

if [[ $# -lt 2 ]] || [[ "$1" == "--help" ]] || [[ "$1" == "-h" ]]; then
	>&2 echo "Usage: moss-find <command> <string> ..."
	if [[ "$1" == "--help" ]] || [[ "$1" == "-h" ]]; then
		exit
	fi
	exit 1
fi

if [[ -z `which moss 2>/dev/null` ]]; then
	>&2 echo "moss-find: moss not installed"
	exit 1
fi

COMMAND=`echo "$@" | cut -d ' ' -f 1`
QUERY=`echo "$@" | cut -d ' ' -f 2- | tr ' ' _`
RESULTS=`find ~/music | grep "$QUERY" | grep \\\\. | sort`
if [[ "$RESULTS" ]]; then
	moss "$COMMAND" "$RESULTS"
else
	>&2 echo "No results for: $QUERY"
	exit 1
fi
