#!/usr/bin/env bash

if [[ $# -lt 2 ]] || [[ "$1" == '--help' ]] || [[ "$1" == '-h' ]]; then
	echo 'Usage: moss-find <command> <string> ...' >&2
	if [[ "$1" == '--help' ]] || [[ "$1" == '-h' ]]; then
		exit
	fi
	exit 1
fi

if [[ -z `which moss 2>/dev/null` ]]; then
	echo 'moss-find: moss not installed' >&2
	exit 1
fi

COMMAND=`echo "$@" | cut -d ' ' -f 1`
QUERY=`echo "$@" | cut -d ' ' -f 2- | tr ' ' _`
RESULTS=`find ~/music | grep "$QUERY" | grep \\\\. | sort | tr '\\n' ' '`
if [[ "$RESULTS" ]]; then
	moss "$COMMAND" $RESULTS
else
	echo "No results for: $QUERY" >&2
	exit 1
fi
