#!/usr/bin/env bash

if [[ $# -lt 2 || "$1" == '--help' || "$1" == '-h' ]]; then
	echo 'Usage: moss-find <command> <string> ...' >&2
	[[ "$1" == '--help' || "$1" == '-h' ]]; exit $?
fi

if [[ -z `which moss 2>/dev/null` ]]; then
	echo 'moss-find: moss not installed' >&2
	exit 1
fi

cmd=`echo "$@" | cut -d ' ' -f 1`
query=`echo "$@" | cut -d ' ' -f 2- | tr ' ' _`
results=`find ~/music | grep "$query" | grep \\\\. | sort | tr '\\n' ' '`
if [[ "$results" ]]; then
	moss "$cmd" $results
else
	echo "No results for: $query" >&2
	exit 1
fi
