#!/usr/bin/env bash

root=~/public/music

if [[ $# == 0 || "$1" == '--help' || "$1" == '-h' ]]; then
	echo 'Usage: musorg <file> ...' >&2
	[[ $# != 0 ]]; exit
fi

if [[ -z `which ffprobe 2>/dev/null` ]]; then
	echo 'musorg: ffprobe not installed' >&2
	exit 1
fi

gettag () {
	echo "$1" | tr '[:upper:]' '[:lower:]' | grep "^    $2 " | \
		sed 's/^.\+: //' | tr -d "'" | \
		tr -s '`~!@#$%^&*()=+[{]}\|;:",<.>/? ' '_' | \
		sed 's/^_//' | sed 's/_$//'
}

status=0

for arg; do
	tags=$(ffprobe "$arg" 2>&1)
	if [[ $? != 0 ]]; then
		echo "$arg: unsupported file format"
		status=1
		continue
	fi

	folder="$root"
	album=$(gettag "$tags" album)
	artist=$(gettag "$tags" artist)
	if [[ $(echo "$arg" | cut -d ' ' -f 1) == BotB ]]; then
		folder="$folder/botb"
	elif [[ "$album" ]]; then
		folder="$folder/$album"
	elif [[ "$artist" ]]; then
		folder="$folder/$artist"
	fi

	track=$(printf %02d $(gettag "$tags" track))
	title=$(gettag "$tags" title)
	ext=$(echo "$arg" | sed 's/.\+\(\..\+$\)/\1/')

	mkdir -p "$folder"
	if [[ "$track" == 00 ]]; then
		mv -nv "$arg" "$folder/$title$ext"
	else
		mv -nv "$arg" "$folder/${track}_$title$ext"
	fi
done

exit $status
