#!/usr/bin/env bash

if [[ $1 = '-h' || $1 = '--help' ]]; then 
	echo 'Usage: nicename [-h] [<arg>]...' >&2
	exit
fi

niceecho () {
	echo "$1" | tr -d "'\")]}>?!" | tr -c [:alnum:]\\n. - | \
	tr [:upper:] [:lower:] | tr -s -
}

if [[ $# -gt 0 ]]; then
	niceecho "$*"
else
	while read line; do
		niceecho "$line"
	done
fi
