#!/usr/bin/env bash

if [[ $# == 0 || "$1" == '--help' || "$1" == '-h' ]]; then
	echo 'Usage: prune <dir> ...' >&2
	[[ $# != 0 ]]; exit
fi

for arg; do
	while true; do
		deleted=$(find "$arg" -type d -empty -execdir rmdir {} ';' 2>&1)
		if [[ -z "$deleted" ]]; then break; fi
	done
done
