#!/usr/bin/env bash

if [[ $# == 0 ]] || [[ "$1" == '--help' ]] || [[ "$1" == '-h' ]]; then
	echo 'Usage: wri <target> ...' >&2
	if [[ $# == 0 ]]; then
		exit 1
	fi
	exit
fi

if [[ -z "$BROWSER" ]]; then
	echo 'wri: $BROWSER not set' >&2
	exit 1
fi

for PROGRAM in ri markdown "$BROWSER"; do
	if [[ -z `which "$PROGRAM" 2>/dev/null` ]]; then
		echo "wri: $PROGRAM not installed" >&2
		exit 1
	fi
done

FILE=/tmp/wri.html
ri -f markdown "$@" | markdown > $FILE
"$BROWSER" "file://$FILE" 2>/dev/null &
