#!/usr/bin/env racket
#lang racket/base

;; This script preprocesses text from stdin for use as a TIPP10 typing tutor
;; lesson.

(require racket/list
	 racket/match
	 racket/stream
	 threading)

(define max-lines 400)
(define min-char-variety 5)
(define replacement-pairs '(("[\t ]+" " ")
			    ("^ " "")
			    (" $" "")))
(define (replace s)
  (foldl (match-lambda**
	   [((list pattern insert) s)
	    (regexp-replace* pattern s insert)])
	 s replacement-pairs))

(define (varied s)
  (>= (length (remove-duplicates (string->list s)))
      min-char-variety))

(~>> (sequence->stream (in-lines))
     (stream-filter varied)
     (stream-map replace)
     (stream-take _ max-lines)
     (stream-for-each displayln))
