#!/usr/bin/env racket
#lang racket/base

(require racket/list
	 racket/match
	 racket/sequence
	 threading)

(define max-lines 400)
(define min-char-variety 5)
(define replacement-pairs '(("[\t ]+" " ")
			    ("^ " "")
			    (" $" "")))
(define (replace s)
  (foldl (match-lambda**
	   [((list pattern insert) s)
	    (regexp-replace* pattern s insert)])
	 s replacement-pairs))

(define (varied s)
  (>= (length (remove-duplicates (string->list s)))
      min-char-variety))

(define (take* i lst)
  (take lst i))

(~>> (in-lines)
     sequence->list
     (filter varied)
     (map replace)
     (take* 400)
     (for-each displayln))
