#!/usr/bin/env python

# this script implements a pipe that "toggles" text between CSV and aligned,
# tab-separated columns.

import csv, io, math,re, sys

tab_width = 8

lines = [line for line in sys.stdin.readlines() if line != '\n']
if any('\t' in line for line in lines):
    # untab
    rows = [[col for col in re.split(r'\t+', line.strip())]
            for line in lines]
    csv.writer(sys.stdout).writerows(rows)
else:
    # tab
    rows = [row for row in csv.reader(io.StringIO(''.join(lines)))]
    target_len = [max(math.ceil((len(row[i]) + 1) / tab_width) * tab_width
                      for row in rows)
                  for i in range(len(rows[0]))]
    print('\n'.join(''.join([col + ('\t' * math.ceil((target_len[i] - len(col)) / tab_width)
                                    if i < len(row) - 1 else '')
                             for i, col in enumerate(row)])
                    for row in rows))
