#!/usr/bin/env bash

if [[ $# == 0 || "$1" == '--help' || "$1" == '-h' ]]; then
	echo 'Usage: wri <target> ...' >&2
	[[ $# != 0 ]]; exit
fi

if [[ -z "$BROWSER" ]]; then
	echo 'wri: $BROWSER not set' >&2
	exit 1
fi

for program in ri markdown "$BROWSER"; do
	if [[ -z `which "$program" 2>/dev/null` ]]; then
		echo "wri: $program not installed" >&2
		exit 1
	fi
done

file=/tmp/wri.html
ri -f markdown "$@" | markdown > $file
"$BROWSER" "file://$file" 2>/dev/null &
